name: {{cookiecutter.package_name}}

channels:
  - pytorch
  - conda-forge

dependencies:
  - python>=3.8
  - numpy
  - scipy
  - matplotlib
  - pandas
  - pytest
  - flake8
  - rope
  - autopep8
  - black
  - click
  - jupyter
  - pyyaml
  - pytorch>=1.6.0
  - torchvision
  - cudatoolkit>=10.0
  - tensorboard>=2.3.0
  - absl-py
  - future
  - tqdm
  - pip
  - pip:
    - -e .  # install package in development mode
